steps:
  - id: 'Populate Maven cache from bucket'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - '-q'
      - 'rsync'
      - '-r'
      - 'gs://hmf-build-caches/serve/.m2'
      - '/cache/.m2'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
  - id: 'Set release version'
    name: 'maven:3.9.2-eclipse-temurin-11'
    entrypoint: mvn
    args: [ 'versions:set', '-DnewVersion=${TAG_NAME}' ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
  - id: 'Compile, package, release'
    name: 'maven:3.9.2-eclipse-temurin-11'
    entrypoint: mvn
    args: [ 'deploy', '-B', '-DdeployAtEnd=true' ]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
  - id: 'Refresh bucket from local Maven cache after build'
    name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - '-q'
      - 'rsync'
      - '-r'
      - '/cache/.m2'
      - 'gs://hmf-build-caches/serve/.m2/'
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
timeout: 4800s
options:
  machineType: 'E2_HIGHCPU_8'
