package com.hartwig.serve.sources.ckb.blacklist;

public enum CkbBlacklistStudyReason {
    ALL_STUDIES_BASED_ON_MOLECULAR_PROFILE,
    STUDY_WHOLE,
    STUDY_BASED_ON_THERAPY,
    STUDY_BASED_ON_THERAPY_AND_CANCER_TYPE,
    STUDY_BASED_ON_THERAPY_AND_CANCER_TYPE_AND_MOLECULAR_PROFILE;
}
